### ISSUE TITLE
Throw creates log in CloudWatch with stack trace

### ISSUE THREAD

**Issue by houmark** [Collaborne/migrate-cognito-user-pool-lambda#2]
Hey guys,

Thanks for this. I already had similar code and came to here as I was searching for solutions to not have flood my log and show invocations as "errored" in Lambda when throwing errors. I mean, throwing errors is considered expected here and not really an error.

My question goes; Are you seeing the same and are you okay with that? If not, maybe I have something wrong or maybe you found a way to swallow the errors in logs?

**Comment by ankon** [comment]
I think we're simply ok with that, it hasn't been a problem in the one place where we needed this. This is ultimately "temporary" code, until the users are migrated or the deadline for the migration has passed.
