### ISSUE TITLE
Trigger not firing when signing in

### ISSUE THREAD

**Issue by Sohaib112** [Collaborne/migrate-cognito-user-pool-lambda#4]
I have followed all the processes mentioned. For the test, I am using this app "https://github.com/dbroadhurst/aws-cognito-react"

My trigger is working fine when I hit the forget password button but it is not firing upon the sign-in process.
I tried passing JSON requests manually and it is working fine. Lambda was able to search and respond back but somehow on the sign-in button trigger is not firing up.

Any help ??

Same issue mentioned here as well "https://stackoverflow.com/questions/62355507/aws-cognito-user-migration-pool-trigger-not-working-on-login-flow"

**Comment by ankon** [comment]
We're using the Amplify parts for interacting with Cognito, no idea about aws-cognito-react.

That said: The trigger only seems to fire when using the user/password auth mechanism, so make sure to configure that and that it is actually getting used.

**Comment by Ashna-softlets** [comment]
> We're using the Amplify parts for interacting with Cognito, no idea about aws-cognito-react.
> 
> That said: The trigger only seems to fire when using the user/password auth mechanism, so make sure to configure that and that it is actually getting used.

@ankon Did u solved this issue

**Comment by ankon** [comment]
@Ashna-softlets there is no an "issue" from what I know with this software, but rather it seems that you need to be checking and double-checking the configuration.
