### ISSUE TITLE
Is possible migrate the user group information

### ISSUE THREAD

**Issue by kamiNaranjo** [Collaborne/migrate-cognito-user-pool-lambda#5]
First, thank you so much for the script, was very usefull. In this moment I need migrate all the user information, I know that I could get the group with adminListGroupsForUser, but I don't know how add it to the new cognito pool. Maybe do you have any idea?

**Comment by ankon** [comment]
We're not using Cognito's groups, so unfortunately no: No idea. This is a good question for a general forum like StackOverflow and/or the AWS developer forums though, so I would suggest you ask there.
