### ISSUE TITLE
How to migrate social signin entries?

### ISSUE THREAD

**Issue by devlegend1** [Collaborne/migrate-cognito-user-pool-lambda#8]
Cognito saves separately for social signIn rows like Google for user pool.
So for one gmail, we can have 2 or more user rows in cognito user pool.
In this case, how can we migrate these social sign in rows?

**Comment by ronnyroeller** [comment]
We don't use social signins. But I guess SSO is similar: we normally don't migrate the Cognito items but let them get recreated (and then we have application logic to connect the new Cognito user to the user in our database (e.g. based on email/unique ID).
Reasoning: The only relevant part are the password that you can't export from Cognito - yet, social signin/SSO by definition don't have any secret data in Cognito.
